### ISSUE TITLE
Vendor description formatting not saved

### ISSUE THREAD

**Issue by rimpab** [dualcube/dc-woocommerce-multi-vendor#1]
**Description -** Going into Users -> All Users, then select a vendor to edit.
Scroll down to "Description", there is a WYSIWYG editor for entering description. I have entered some text with formatting as the description.

However, after clicking "Update User", all formatting (bold, line-breaks, etc) seems to have lost. No formatting was shown on the vendor's page and product page.

**Comment by arkaprava-dc** [comment]
Go to "class/class-wcmp-user.php" line 1002 and add the below code
```
elseif ( $fieldkey == 'vendor_description' ) {
      update_user_meta( $user_id, '_' . $fieldkey, $_POST[ $fieldkey ] );
 }
```

**Comment by rimpab** [comment]
I was looking to find out why the stripe massive pay didn’t pay the commission,
and I’ve found thant at this line: $total_stripe_ammount = $total*100; (class-wcmp-stripe-gateway-massivepay.php)
you didn’t convert double values in integer value.
I’ve change the line in this way: $total_stripe_ammount = intval ($total*100);

Note: the stripe documentation reports :
amount
REQUIRED
A positive integer in cents (or 0 for a free plan) representing how much to charge (on a recurring basis)
