### ISSUE TITLE
Vendor Shop Title Update Error

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/dc-woocommerce-multi-vendor#11]
Some vendors are facing  error "Shop Title Update Error" while changing the "Store Name" and "Store Slug" .

**Comment by subrata-dc** [comment]
Fixed [2724c8f](https://github.com/dualcube/dc-woocommerce-multi-vendor/commit/2724c8f35c7639fe884d97ce56118ae79abf1df6)
