### ISSUE TITLE
Variations and Attributes

### ISSUE THREAD

**Issue by handcraftedla** [dualcube/dc-woocommerce-multi-vendor#15]
We are not able to get the attributes to work. [https://handcraftedla.com/wp-content/uploads/2017/08/Screenshot-2017-08-24-11.41.39.png](url) there are js issues. We are opening in a week and really need this fixed. Thanks!

**Comment by handcraftedla** [comment]
https://handcraftedla.com/wp-content/uploads/2017/08/Screenshot-2017-08-24-11.41.39.png

**Comment by subrata-dc** [comment]
@handcraftedla 
It's a javascript error from app.js of some other plugin or theme we did't use any javasctipt file name with app.js
