### ISSUE TITLE
Fatal error: Cannot redeclare class scss_formatter_nested in /wp-content/plugins/dc-woocommerce-multi-vendor/lib/php/scss.inc.php on line 4323

### ISSUE THREAD

**Issue by surindersammy** [dualcube/dc-woocommerce-multi-vendor#23]
I installed the plugin and add Vendor Dashboard in Menu. When clicked on this menu getting this error

Fatal error: Cannot redeclare class scss_formatter_nested in /wp-content/plugins/dc-woocommerce-multi-vendor/lib/php/scss.inc.php on line 4323

**Comment by subrata-dc** [comment]
@surindersammy 
We have removed the SCSS library in our next version 3.0.

**Comment by surindersammy** [comment]
I installed it today

**Comment by subrata-dc** [comment]
@surindersammy We are hoping to publish the Beta version of our version 3.0, hopefully within two days. 

We will definitely keep you posted :-)
