### ISSUE TITLE
Commission from addons is calculated incorrectly

### ISSUE THREAD

**Issue by joshuatf** [dualcube/dc-woocommerce-multi-vendor#24]
For plugins that append product addons (like Woocommerce Addons- not variations), commission will always be calculated from the product price and ignore addons.

In the function get_item_commission, lines 272-279 in class-wcmp-calculate-commission.php, the commission is always marked down to be no greater than the product price.

```php                   
$product_value = get_post_meta($product_id_for_value, '_price', true);
if (empty($product_value)) {
    $product_value = 0;
}
$product_value_total += ($product_value * $item['qty']);
if ($amount > $product_value_total) {
    $amount = $product_value_total;
}
```

I assume this is some kind of failsafe to prevent overpaying commissions, but it will cause calculation problems with any non-standard products.  I think removing this would be best, but alternatively adding the product vars ($product_id, $variation_id, $item, $order_id, $item_id) to the vendor_commission_amount filter would allow this to be overridden manually.

**Comment by subrata-dc** [comment]
@joshuatf 
We have solved this issue in 3.0.5 please check.
