### ISSUE TITLE
Page Template for Vendor Shop 

### ISSUE THREAD

**Issue by kulchanjagat** [dualcube/dc-woocommerce-multi-vendor#25]
Is there any way to display products of respective shop/vendor in the template page. By default, vendor shop is displaying in archive-product.php. please help me out.

**Comment by subrata-dc** [comment]
@kulchanjagat 
Yes, you are right vendor shop page render from the archive-product.php file they are nothing but the taxonomy of WooCommerce product. Coming to your query, is that you want to create a different page and display vendor products on it?
