### ISSUE TITLE
Not translated string

### ISSUE THREAD

**Issue by CasperBraske** [dualcube/dc-woocommerce-multi-vendor#28]
The placeholder text is not translated.

https://github.com/dualcube/dc-woocommerce-multi-vendor/blob/9c7f9d24a48c593fb7be0f1edf0e59b4f5f783a6/admin/class-wcmp-settings-payment.php#L62

**Comment by subrata-dc** [comment]
@CasperBraske 
Thanks for reporting the translation issue we will surely fix this in next update.
