### ISSUE TITLE
Trailing white space in translation strings

### ISSUE THREAD

**Issue by CasperBraske** [dualcube/dc-woocommerce-multi-vendor#32]
Please, remove the [white spaces left in translated strings](https://github.com/dualcube/dc-woocommerce-multi-vendor/blob/master/languages/dc-woocommerce-multi-vendor.pot#L3454). If you need space between words, do it outside of the string.
They are causing translation to not match with the source and people using software like Poedit or WP Translate service will not be able to see them.

Best regards.

**Comment by subrata-dc** [comment]
@CasperBraske 
Thanks for pointing out the issue. We will try to fix this in next update.

**Comment by sushobhan-pal** [comment]
We have fixed #32 issue in our 3.0.6 version.
