### ISSUE TITLE
Override templates file not working

### ISSUE THREAD

**Issue by basherr** [dualcube/dc-woocommerce-multi-vendor#39]
I have been trying to overwrite the files but does not seem to be working.  The file that I copied to `child-theme` and replace with empty content:
[Add Product](https://github.com/dualcube/dc-woocommerce-multi-vendor/blob/master/templates/vendor-dashboard/product-manager/add-product.php)

I did follow the given  [steps](https://wc-marketplace.com/knowledgebase/wcmp-overriding-templates/).

Here's the directory structure for the aforementioned file:
`zass-child\dc-product-vendor\templates\vendor-dashboard\product-manager`

Regards,
Basheer A

**Comment by sushobhan-pal** [comment]
Hi @basherr ,
You need to remove "templates" folder in that directory structure. In your case, the structure should be as follows - 
`zass-child\dc-product-vendor\vendor-dashboard\product-manager`
Do this, and it will work.
Regards
Sushobhan

**Comment by basherr** [comment]
@sushobhan-pal Thank you ver much!
