### ISSUE TITLE
Documentation for php?

### ISSUE THREAD

**Issue by HW-Siew** [dualcube/dc-woocommerce-multi-vendor#41]
hi, may i where can i see the documentation for php?

For example, how to query products, category and etc?
Thanks in advance

**Comment by sushobhan-pal** [comment]
Can you please be more specific? Also, as I can see, you have reached us via WordPress forum. I'll request you to maintain one single thread for support. It will be easier for us to provide better assistance in that way.
For now, I am escalating your issue to our support team and they will response you via WordPress forum.  Thanks for reaching us and I'm closing this thread here.
