### ISSUE TITLE
WCMp Multi-Currency Support for WooCommerce PBC

### ISSUE THREAD

**Issue by Archie97** [dualcube/dc-woocommerce-multi-vendor#47]
We’re trying to setup WCMp(https://wc-marketplace.com/) on our WordPress Instance, with which WC PBC doesn’t seem to be working well.
Here you can see the three images: (https://imgur.com/a/Jr3S3yG)

Vendor’s commission amount seems fine on Image 0, as you can see. Vendor’s commission is $179.
Then on Image 1 and Image 2, it's displayed as 179 INR and Vendor just receives 179 INR instead of $179.

How can we provide support for [WooCommerce PBC](https://www.pricebasedcountry.com/)

WooCommerce Status [Report](https://gist.githubusercontent.com/Archie97/7fc726e53b9495cbbda8a4fb4b67112c/raw/a43a94141d9eec0fc8c87285482e967457bf60f5/wc_status_reportmd)

**Comment by khokandc** [comment]
@Archie97, currently we haven't compatibility with Woocommerce PBC. So you have to R&D the plugin's code very well to make compatible with WCMp. Please check how the plugin changed the price based on shopper country and you have to follows the same and converted the actual prices using pricing zone settings value ( calculated prices by exchange rate ). For ref. [you can check order total](https://www.pricebasedcountry.com/wp-content/uploads/2017/09/receive-payments-in-multiple-currencies.jpeg), how it change the order total price based on shopper zonal price.

**Comment by khokandc** [comment]
@Archie97, currently we are working on some upcoming milestone for WC Marketplace, and I am afraid we don't have any planning to work on PBC yet. However, we have added this in our future roadmap. If we do start working on this, we will let you know. 

Regarding the pages, there are many pages and functionality, where we include commission. So. it will be difficult for us to guide you with all the details in short. The best way will be for you, to study our plugin i.e. admin and vendor end and check where we display the commissions.
