### ISSUE TITLE
Bug - Capabilities remain same after changing from vendor to other user roles

### ISSUE THREAD

**Issue by rimpab** [dualcube/dc-woocommerce-multi-vendor#5]
When I checked the user role from vendor to customer, subscriber or other user roles, the capability is remaining same as vendor's user role.

**Capabilities:**

publish_shop_coupons, assign_product_terms, upload_files, edit_product, delete_product, edit_products, edit_others_products, delete_published_products, delete_products, delete_others_products, edit_published_products, read_product, read_shop_coupon, edit_shop_coupons, read_shop_coupons, delete_shop_coupons, edit_published_shop_coupons, delete_published_shop_coupons, edit_others_shop_coupons, delete_others_shop_coupons, edit_shop_coupon, delete_shop_coupon, edit_posts

**Comment by subrata-dc** [comment]
Issue has been resolved in wc-marketplace version 2.4.5
