### ISSUE TITLE
Single Product Multiple Vendors (SPMV)

### ISSUE THREAD

**Issue by cingrosso** [dualcube/dc-woocommerce-multi-vendor#51]
Despite setting _**"Allow multiple vendors to sell the same product. Buyers can choose their preferred vendor."**_
The product will not show on any vendors unless you assign a product to a particular vendor, in which case it will only show on that vendor's shop.
**How can I create a single product and ensure it appears on all vendors' shops?**

**Comment by khokandc** [comment]
@cingrosso When a vendor adds a existing product to their shop, this product will be displayed in that vendor's shop only. Here is our document, that might help you out with this flow - https://wc-marketplace.com/knowledgebase/setting-assign-single-product-multiple-seller/

Therefore, if admin has a product A and Vendor A has also added this product, then vendor A's store will only have his product.

Now, the shop page will show the lowest amount product amongst them, and you can change this using this settings "Show SPMV products" (see this screenshot - https://prnt.sc/mk1tno)
