### ISSUE TITLE
dont show changes in server site

### ISSUE THREAD

**Issue by omkarjadhav1997** [dualcube/dc-woocommerce-multi-vendor#52]
sir i copy vendor_registration_form.php copy file as it is in  yourtheme/dc-product-vendor/vendor_registration_form.php but it dont show any changes in server site registration form the what should i do

**Comment by khokandc** [comment]
@omkarjadhav1997 have you modified any part of the vendor_registration_form.php in the copied template? If yes, only then the modified version will be reflected.
