### ISSUE TITLE
Warning: join(): Invalid arguments passed in C:\xampp\htdocs\wordpress\wp-includes\category-template.php on line 1176

### ISSUE THREAD

**Issue by orcacompany** [dualcube/dc-woocommerce-multi-vendor#53]
Warning: join(): Invalid arguments passed in C:\xampp\htdocs\wordpress\wp-includes\category-template.php on line 1176
![Screenshot (2)](https://user-images.githubusercontent.com/46829180/54088983-7b8edd00-436c-11e9-871e-60574862e2c8.png)

**Comment by moumitahalder** [comment]
Hi, sorry to hear that.

Can you just disable all the plugins except WooCommerce and WC Marketplace and check again. If the issue still exist, please switch to some default theme like Twenty Sixteen and check again. 

Let us know the result so we can help you out further.
