### ISSUE TITLE
Astra Theme conflict with your plugin.

### ISSUE THREAD

**Issue by premanshup** [dualcube/dc-woocommerce-multi-vendor#57]
Hello,

I'm one of the developers of theme Astra. When the Astra theme is active along with your plugin, a warning comes on the Store page.

Please see the screenshot below:
https://cl.ly/221cda5aa10a

We looked into your code and found that you guys are adding a filter in file 

wp-content\plugins\dc-woocommerce-multi-vendor\classes\class-wcmp-product.php

Line: 115

add_filter( 'term_links-product_cat', array($this, 'show_default_product_cats_product_single'), 99);

Now, the function called on this filter does not return anything when called from the shop page which produces the warning.

Which is due to this condition - if(is_product() && $product){  -> Line: 1813

Now, Astra calls WooCommerce function wc_get_product_category_list() which internally triggers the filter which is getting modified by the above filter in your code.

Suggestion/Solution - Can you please check if(is_product() && $product){  this condition when adding the filter? So that this will not be triggered unless it is a product page.

Now your code/condition from line 1813 will be removed and will be added to line 115 of the same file.

if(is_product() && $product){
   add_filter( 'term_links-product_cat', array($this, 'show_default_product_cats_product_single'), 99);
}

I hope this will be looked into. Let me know if I'm missing something or if there is any other solution. Looking forward to resolve this warning :-)

**Comment by moumitahalder** [comment]
@premanshup, thanks for sharing the information.

Our team will check this and get back to you.

**Comment by itzmekhokan** [comment]
@premanshup, can you check our git version with your theme.

**Comment by premanshup** [comment]
@itzmekhokan Thank you for the response, but this still did not fix the issue. I have opened a merge request, please check it #58
