### ISSUE TITLE
Can we set the specific image sizes for vendor?

### ISSUE THREAD

**Issue by kaushikrohit54** [dualcube/dc-woocommerce-multi-vendor#59]
I want to set the specific image size for vendor below that or above that it should show error to vendor.

**Comment by khokandc** [comment]
@kaushikrohit54 if you want to specify image sizes for vendor store logo and cover, you can achieve that by using this `apply_filters( 'wcmp_frontend_dash_upload_script_params', $script_data )` filter and pass your specific image sizes. Or if you want to restrict sizes rest of the section including store logo and cover, you can simply use wordpress filter `apply_filters( "wp_handle_upload_prefilter", $file )` and do your modification.
