### ISSUE TITLE
WC Marketplace Making Website Slow

### ISSUE THREAD

**Issue by rimpab** [dualcube/dc-woocommerce-multi-vendor#7]
Hi Team,

We are an online fashion retailer. We use the WC Marketplace plugin for the various vendors we have.

Our Hosting solution provider – Pressable has done some extensive research and told us that the WCMP plugin is causing our website to run extremely slow.

Here is what they had to say:

The biggest offender here is dc-woocommerce-multi-vendor, which looks like it is named WC Marketplace in the dashboard.

This plugin is running 6 massive update queries on every page load and two “create if not exists” table creation queries. This plugin by itself is the largest contributing factor to the slowness aside from the ultimate-member rewrite issue. Here are the queries it is running on each page load:

https://gist.githubusercontent.com/iamrobertv/f16122bdb972e5a2ed6f03586ffd8965/raw/41de7483bd050236364e3c375836b3f379098287/gistfile1.txt

I would highly recommend showing these queries to the developer and asking why these queries are being run and see if they can help you sort this out. If you disable this plugin, your site loads much much faster.

Beside this, this site has so much plugin bloat that definitely isn’t helping, but ultimately, it still loads relatively quickly without WC Marketplace active.

**Comment by subrata-dc** [comment]
Issue has been resolved in wc-marketplace version 2.4.5
